### ISSUE TITLE
~33%, not ~50%

### ISSUE THREAD

**Issue by joeycozza** [alexhultman/Response-to-V8-claims#3]
I get your point and agree with you. But 0.75 vs 1.1 is much closer to 33%, not 50%.  I know you used a ~, but the difference between 1/3 and 1/2 is significant in my opinion.

**Comment by alexhultman** [comment]
The point is really not to establish some kind of magic number like "JavaScript is 50% slower than C++". I have many pieces of complex code where the JS equivalent is 2000% slower. The point is, given this very minimal example that V8 devs fabricated, I can make the results differ more.

0.75 + (0.75 * 0.5) = 1.125

Have 0.75 seconds, add 50%, get 1.1 seconds.

**Comment by joeycozza** [comment]
Like I said, I understood your point, I just misunderstood where you got your 50%. I closed the issue when I realized where you got your 50%, like 1 minute after I posted the issue. Too bad I couldn't delete it from existence.

**Comment by alexhultman** [comment]
Well both 33% and 50% are equally correct. It depends on what way you look.
